fieldLayouts:
  0614a0e3-bcbc-4385-9b3b-bdffed1490a7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e6b4a927-46f7-4a4d-a7b9-4d904c5b1059
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e453e60d-dd8f-4920-97b2-5418e05af41f # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1cc1b12e-0c2e-475b-8553-ee14f67e7299
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: db3f23c3-b8fc-4b52-a266-104c42fae4d4 # Blogs Category's
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8086ae45-8e49-4560-8717-fcddcb0c274f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd9130b3-b9dd-4d0a-8a47-4c007492ec95 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3db4cd6-cb17-45c3-9432-2dc438606853
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a51f3b8e-e933-4ea5-a1e6-dee6bb257655
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: bde721cc-efcf-4a13-b9b1-139147fe75bc # Blogs
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
