fieldLayouts:
  b8efd56f-6068-4471-9629-e196c60abaae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 38c007b2-a7ef-4735-beb7-91d0e952742e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e453e60d-dd8f-4920-97b2-5418e05af41f # Image
            instructions: null
            label: 'Profile Photo'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e41edb71-874c-4c2b-ad15-382d4c8c7dbe
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1ecd3d55-312c-4938-b20e-50854a45d8a9 # Popup Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83da8b9f-f815-416a-aa36-fe85e1cf86bf
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 82bec9fd-f166-4176-9f60-af0b9b098db5 # Designation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26a2ef44-89f3-45e7-824e-22dda3a669f8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 14b55430-d32a-4272-912c-76b2faafe6a6 # Country
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a91bdb02-79b6-480a-8704-3385ec5650f4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: dd9130b3-b9dd-4d0a-8a47-4c007492ec95 # Text
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc6e8424-67de-4c8b-be01-04c9336ccdce
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 274dcdb5-7def-483d-a244-556eb12cf57c
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: efff6f15-1197-46ea-ad67-947c87fe75a8 # Teachers
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
