columnSuffix: null
contentColumnType: string
fieldGroup: a647e025-4229-4ca3-87f2-9e58f43dbf34 # Common
handle: blogsCategorys
instructions: null
name: 'Blogs Category''s'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: 1
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:b9f175f8-a4e6-456f-bc90-8a10291d3782' # Blog
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
