defaultPlacement: end
enableVersioning: true
handle: teachers
name: Teachers
propagationMethod: all
siteSettings:
  423d37d6-7c8f-40b6-9631-4c335f47efed: # Craft demo
    enabledByDefault: true
    hasUrls: true
    template: teachers/_entry
    uriFormat: 'teachers/{slug}'
type: channel
